"""delete column note

Revision ID: 14df34c2b17b
Revises: 5a269eb3f4d5
Create Date: 2025-09-27 17:06:07.257638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14df34c2b17b'
down_revision = '5a269eb3f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseller_stock_outs', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseller_stock_outs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
