"""add relation colum

Revision ID: 29e4dbdff7a3
Revises: da3f058ee3a2
Create Date: 2025-09-18 16:56:14.346858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e4dbdff7a3'
down_revision = 'da3f058ee3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_detail_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_return_transaction', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'return_transactions', ['id_return_transaction'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_detail_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_return_transaction')

    # ### end Alembic commands ###
