"""Add stock out model

Revision ID: 5a269eb3f4d5
Revises: da3f058ee3a2
Create Date: 2025-09-27 17:04:13.553430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a269eb3f4d5'
down_revision = 'da3f058ee3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller_stock_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reseller', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_reseller'], ['resellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reseller_stock_out_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_stock_out', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_stock_out'], ['reseller_stock_outs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_detail_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'return_transactions', ['id_return_transaction'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_detail_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('reseller_stock_out_details')
    op.drop_table('reseller_stock_outs')
    # ### end Alembic commands ###
