"""add columns to product

Revision ID: 79b241ba3d06
Revises: be578ab32989
Create Date: 2025-12-19 07:33:01.039105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b241ba3d06'
down_revision = 'be578ab32989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('item_series', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('item_series')
        batch_op.drop_column('item_code')

    # ### end Alembic commands ###
